# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: home
    url: /
    weight: 10
  - name: About Us
    identifier: about-us1
    url: '#about-us'
    parent: home
    weight: 11
  - name: Current Projects
    identifier: currentprojects
    url: '#projects'
    parent: projects
    weight: 12
  - name: Success Highlights
    identifier: success
    url: /event/first-airbnb-live-videostream-from-tegla-loroupe-refugee-olympic-team-training-center-in-ngong-kenya
    parent: home
    weight: 13
  - name: Partners
    identifier: partners
    url: /post/our-partners
    pageRef: /post/partners
    parent: home
    weight: 14
  - name: People
    parent: home
    url: /authors
    weight: 15
  - name: About Us
    url: /home/about-us
    identifier: about-us
    weight: 20
  - name: Mission
    identifier: mission
    parent: about-us
    url: /home/about-us
  - name: History
    parent: about-us
    url: /courses/Sports-in-Kenya
    weight: 25
  - name: Projects
    identifier: projects
    url: 
  - name: News
    url: post
    weight: 20
  - name: People
    url: authors
    weight: 30
  - name: Events
    url: event
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Contact
    url: contact
    weight: 60