# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[[menu]]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 20

  [[menu.main]]
    name = "Academic"
    parent = "tags"
    url = "tags/academic/"
    weight = 10

  [[menu.main]]
    name = "About Us"
    url = "#about-us"
    weight = 20

  [[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 30

  [[menu.main]]
    name = "Media Center"
    url = "post"
    weight = 40

  [[menu.main]]
    name = "Support/Join Us"
    url = "donate"
    weight = 50

  [[menu.main]]
    name = "Contact Us"
    url = "contact"
    weight = 60

# [[main]]
#  name = "Blog"
#  url = "blog"
#  weight = 20

# [[main]]
#  name = "People"
#  url = "people"
#  weight = 30


# [[main]]
#  name = "Events"
#  url = "event"
#  weight = 40

#[[main]]
#  name = "Talks"
#  url = "talks"
#  weight = 41

#[[main]]
#  name = "Publications"
#  url = "publications/"
#  weight = 50

  [[menu.main_right]]
    name = "Courses"
    url = "courses/"
    weight = 70


#[[menu.main]]
#  name = "Slides"
#  url = "slides/slides"
#  weight = 80

  [[menu.main_right]]
    name = "Tutorial"
    url = "Tutorial"
    weight = 80


  # Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 80
